<?php
/**
 * Created by PhpStorm.
 * User: brahmani
 * Date: 15/11/18
 * Time: 16.00
 */

namespace ReplyITUtils;

use Shopware\Components\Plugin;
use Shopware\Components\Plugin\Context\InstallContext;
use Shopware\Components\Plugin\Context\UninstallContext;

class ReplyITUtils extends Plugin
{
    public function install(InstallContext $context)
    {
        parent::install($context); // TODO: Change the autogenerated stub
    }

    public function uninstall(UninstallContext $context)
    {
        parent::uninstall($context); // TODO: Change the autogenerated stub
    }

}